AWSTemplateFormatVersion: 2010-09-09

Resources:
  ManagementVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: <%=env_network_cidr%>
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: <%=env_name%>

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ManagementVPC
      CidrBlock: <%=env_network_cidr%>
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: <%=env_name%>
        
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Name
          Value: <%=env_name%>

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: ManagementVPC
      InternetGatewayId:
        Ref: InternetGateway        

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: ManagementVPC
      Tags:
        - Key: Environment
          Value: <%=env_name%>
        - Key: Network
          Value: public
        - Key: Name
          Value: public-<%=env_name%>

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway        

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicRouteTable

  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: ManagementVPC
      Tags:
      - Key: Environment
        Value: <%=env_name%>
      - Key: Network
        Value: public
      - Key: Name 
        Value: public-<%=env_name%>

  InboundPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: PublicNetworkAcl
      RuleNumber: '100'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '0'
        To: '65535'

  OutboundPublicNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: PublicNetworkAcl
      RuleNumber: '100'
      Protocol: '6'
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '0'
        To: '65535'

  PublicSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      NetworkAclId:
        Ref: PublicNetworkAcl

Outputs:
  ManagementVpcId:
    Description: Management VPC ID
    #Value: { "Fn::GetAtt" : [ "ManagementVPC", "VpcId"] }
    Value:
      Ref: ManagementVPC
  PublicSubnetId:
    Description: Public Subnet ID
    #Value: { "Fn::GetAtt" : [ "PublicSubnet", "SubnetId"] }
    Value:
      Ref: PublicSubnet
